version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: my_online_store_db_2qlb_user
      POSTGRES_PASSWORD: kB695CyygFT2wqkRZulCRLa9lR8JainN
      POSTGRES_DB: my_online_store_db_2qlb
    ports:
      - "5433:5432"   # <— sadece HOST’ta 5433; container içinde her zamanki gibi 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  onlinestore:
    container_name: onlinestore
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"          # <— container→postgres arası her zaman 5432
      DB_NAME: my_online_store_db_2qlb
      DB_USERNAME: my_online_store_db_2qlb_user
      DB_PASSWORD: kB695CyygFT2wqkRZulCRLa9lR8JainN
      DB_SSLMODE: disable
    ports:
      - "127.0.0.1:8080:8080"
      - "18080:8080"
    depends_on:
      postgres:
        condition: service_healthy
