server:
  port: 8080

# PostgreSql Database Config
spring:
  application:
    name: onlinestore
  datasource:
    url: jdbc:postgresql://dpg-d0gdrok9c44c73fg4tn0-a.oregon-postgres.render.com:5432/my_online_store_db_ia8b?sslmode=require
    username: my_online_store_db_ia8b_user
    password: RMBOldznZwrDHIiIWlAreBVzs03LnCgP
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


# health check kontrolü
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info