server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info

spring:
  application:
    name: onlinestore

  datasource:
    # Lokal (Compose): postgres:5432 / my_online_store_db_2qlb  (sslmode=disable)
    # Render: ${DB_HOST}:${DB_PORT}/${DB_NAME}                   (sslmode=require)
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      max-lifetime: ${DB_MAX_LIFETIME:600000}
      connection-timeout: ${DB_CONN_TIMEOUT:30000}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
