apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinestore-deployment
  labels:
    app: onlinestore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onlinestore
  template:
    metadata:
      labels:
        app: onlinestore
    spec:
      containers:
        - name: onlinestore
          image: ipekimnci/onlinestore:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"       # k8s içinde Postgres varsa Service adını yaz; dış servis ise host adını yaz
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "my_online_store_db_2qlb"
            - name: DB_USERNAME
              value: "my_online_store_db_2qlb_user"
            - name: DB_PASSWORD
              value: "kB695CyygFT2wqkRZulCRLa9lR8JainN"
            - name: DB_SSLMODE
              value: "disable"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
