apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinestore-deployment
  labels:
    app: onlinestore
spec:
  replicas: 3  # Uygulamanın 3 örneği çalışacak
  selector:
    matchLabels:
      app: onlinestore
  template:
    metadata:
      labels:
        app: onlinestore
    spec:
      containers:
        - name: onlinestore
          image: ipekimnci/onlinestore:latest  # Docker imajınızın adı
          ports:
            - containerPort: 8080  # Uygulamanızın çalıştığı port
          env:
            - name: DB_HOST
              value: "dpg-d2gse675r7bs73fe2jp0-a.oregon-postgres.render.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "my_online_store_db_2qlb"
            - name: DB_USERNAME
              value: "my_online_store_db_2qlb_user"
            - name: DB_PASSWORD
              value: "kB695CyygFT2wqkRZulCRLa9lR8JainN"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
